### ISSUE TITLE
Native method not found

### ISSUE THREAD

**Issue by smkazemi** [fishwjy/VideoCompressor#14]
Must use NDK ?

```
 Caused by: java.lang.UnsatisfiedLinkError: Native method not found: compressor.VideoController.convertVideoFrame:(Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIII)I
                                                                               at compressor.VideoController.convertVideoFrame(Native Method)
                                                                               at compressor.VideoController.convertVideo(VideoController.java:633)
                                                                               at compressor.VideoCompress$VideoCompressTask.doInBackground(VideoCompress.java:51)
                                                                               at compressor.VideoCompress$VideoCompressTask.doInBackground(VideoCompress.java:32)
                                                                               at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230) 
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
                                                                               at java.lang.Thread.run(Thread.java:838) com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

```
How to Solve ?

**Comment by rpandey66** [comment]
Caused by: java.lang.NoSuchMethodError: No virtual method before(Lorg/aspectj/lang/JoinPoint;)V in class Lcom/googlecode/mp4parser/RequiresParseDetailAspect; or its super classes (declaration of 'com.googlecode.mp4parser.RequiresParseDetailAspect' appears in /data/app/com.udown-DeVSTkUu2N5C4LdxxHGH-g==/base.apk:classes10.dex)

How to resolve this
